### ISSUE TITLE
[Enhancement] rain in cave

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1144] opened 2020-10-04 16:20 UTC
_Originally written by **Mutedmirth | 76561198046014700**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD A8-9600 RADEON R7, 10 COMPUTE CORES 4C+6G  
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **The Eastern Isles New** 
Map: Rival_Shores

*Expected Results:* No rain in cave when I log in
*Actual Results:* Rain in cave although it seems to be only visual
*Replication:* Safe log out while in a cave, then log back in while raining.
Location: X=229802.000 Y=195102.000 Z=14351.153

**Comment by tinystarpaws** [comment] 2021-03-14 20:50
Cannot reproduce, seems fixed with the new storm system.

**Comment by Predatoria** [comment] 2021-03-17 21:31
Should be fixed with the new weather rain particle effects.

**Closed as completed by Predatoria** 2021-03-17 21:31 UTC
Labels: Enhancement, Live, Map
