### ISSUE TITLE
[Bug] Trees Can Cause fall damage when darting out of water.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#357] opened 2020-08-09 09:06 UTC
_Originally written by **Captain z | 76561198410348236**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD Ryzen 5 2600X Six-Core Processor           
Vendor: AuthenticAMD
GPU Brand: AMD Radeon RX 5700
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Mosa** 
Map: Rival_Shores

Some trees if u land on them when darting out of water u take damage, Pls fix

**Comment by Trip-Trap** [comment] 2020-08-13 16:19
Not a bug, will close the issue.

**Closed as completed by Trip-Trap** 2020-08-13 16:19 UTC
Labels: bug, wontfix, Gameplay, Live
