### ISSUE TITLE
[Bug] got teleported and drowned

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#241] opened 2020-07-01 17:52 UTC
_Originally written by **-____- | 76561198402383586**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 970
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **yes** 
Map: Rival_Shores

im a baby rex and my parents where holding me walking over land brige from forest to jungel and i just got teleported in the water and drowned

**Comment by Thy-Vipe** [comment] 2020-07-04 09:09
I'm not sure what would cause such a thing, and the context makes it hard to figure out.
@Predatoria  do you have any idea?

**Comment by Predatoria** [comment] 2020-07-04 14:02
Sounds to me like a variant of the grab / teleport to the origin on the owning client bug.

**Comment by Predatoria** [comment] 2020-08-15 21:11
Duplicate of 297. Going to close this

**Closed as completed by Predatoria** 2020-08-15 21:11 UTC
Labels: bug, Gameplay, Live, duplicate
