### ISSUE TITLE
[Major Bug] crash caused me to lose an inherit

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#455] opened 2020-08-13 22:37 UTC
_Originally written by **Daddy Draco | 76561198101239550**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

i was playing elasmo and just got to .5 growth when the server crashed. I had +2 strong bones and +1 rich blood
when i got back into the game i was .43 growth so i grew a bit more but i never got my +1 rich blood inherit

**Comment by Predatoria** [comment] 2020-08-14 18:22
Duplicate of 464

**Closed as completed by Predatoria** 2020-08-14 18:22 UTC
Labels: Major Bug, Gameplay, Live, duplicate
