### ISSUE TITLE
[Bug] Icthy state jam when water rises above it and it tries to stand up

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#212] opened 2020-06-25 16:36 UTC
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Icthyovenator** 
Map: Rival_Shores

Was at ptera mountain, resting under some shelter and a flood brought the water above my head while I was resting. When i stood up I was stuck, had to use unstuck to get free again.

**Comment by Predatoria** [comment] 2020-06-27 16:48
I tried resting with ichthy (and megalo) and raising the water level.  Both were able to stand up and swim off just fine.  I cannot seem to reproduce this.

**Comment by Trip-Trap** [comment] 2020-06-28 11:30
@Predatoria It likely only works with natural tide. There is a hitch (your character will be moved basically) when the transition from "land" to "water" happens. If you try to stand up in that moment it will jam you

https://youtu.be/jYu_5qF2bhA

**Comment by Predatoria** [comment] 2020-06-30 03:30
This is really strange.  I still cannot reproduce it, even by following this exactly.

**Comment by Trip-Trap** [comment] 2020-07-02 00:05
Closing this for now due to not seeming to be reproducable.

**Closed as completed by Trip-Trap** 2020-07-02 00:05 UTC
Labels: bug, Gameplay, tester-team, Can't reproduce
