### ISSUE TITLE
[Quality of life] Animation suggestions for ory on test

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#148] opened 2020-06-19 15:41 UTC
_Originally written by **SunnyD | 76561198274255587**_
Game Version: 1.1.947

*===== System Specs =====
CPU Brand: AMD FX(tm)-4300 Quad-Core Processor            
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 2
===================*
Context: **Oryctodromeus** 
Map: Rival_Shores

For one thing the breathing details, while lovely when it sleeps, I dont think the cloaca should move as much and its abit..weird..
And if something can be done about the way the animations very quickly snap from one to the other while sitting or eating is abit jarring.
Its probably already known, but the camera on the selection screen for ory is also very far off from the actual dinosaur.
And then on the talent screen, two of the dirt related talents on the attack tree are invisible. Probably known, but just in case I'll still report ^^

**Comment by Predatoria** [comment] 2020-06-21 17:00
Snapping of anims is a duplicate - has been marked as fixed next tester build.

I lowered the sleeping animation speed.  We may need Callie to help with the 'cloaca' issue.

I'm assigning the icons (Burrow Master and Dirt Carry) to Soals, as I can confirm they do not show up well on the talent tree due to the icons being too dark.

Camera issue on dino select is true for velo as well.  I'll assign that to Vipe.

I also told SunnyD to, in the future, report issues as separate bugs rather than reporting several together like this.

**Comment by Predatoria** [comment] 2020-06-25 03:36
Gonna mark this as fixed / closed.  Everything but the bad weight painting has been fixed here now.

**Closed as completed by Predatoria** 2020-06-25 03:36 UTC
Labels: Quality of life, tester-team, Fixed!, Animation
