### ISSUE TITLE
[Bug] Falling through map as ory

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#330] opened 2020-07-30 02:48 UTC
_Originally written by **Death | 76561198228120624**_
Game Version: 1.1.979

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: Radeon (TM) RX 480 Graphics
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Ory** 
Map: Rival_Shores

I was building up in a hole with dirt next to a log and i guess it glitched out and fell into the void of the world then landed in water until i was then tele'd back up to the surface.

**Comment by Predatoria** [comment] 2020-07-31 15:53
Duplicate of 334.

**Closed as completed by Predatoria** 2020-07-31 15:53 UTC
Labels: bug, Map, public_testing, duplicate
