### ISSUE TITLE
[Quality of life] Not able to eat plants sometimes

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#481] opened 2020-08-15 00:49 UTC
_Originally written by **Cynax | 76561199074796396**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **My apa, para, sai, and lurdu. And I'm sure it does it for all other herbies.** 
Map: Ancestral_Plains

As I've noticed ever since the new patch, sometimes when something picks up plants and drops them down, they are bunched up and not able to eat them.

**Comment by Predatoria** [comment] 2020-08-15 21:15
This is a duplicate of a bug we had reported and fixed more recently.  I'm going to close this.

**Closed as completed by Predatoria** 2020-08-15 21:15 UTC
Labels: Quality of life, Gameplay, Live, Fixed!
