### ISSUE TITLE
[Bug] Making a burrow entrance will place Ory above ground

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#188] opened 2020-06-22 21:52 UTC
_Originally written by **TripTrap | 76561198378851871**_
Game Version: 1.1.952

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Orycto** 
Map: Rival_Shores

*Expected Results:* Orys feet always touching the ground while moving.
*Actual Results:* If you finish making an burrow entrance the model will be placed a bit above ground.
*Replication:* Spawn as Ory, make a burrow entrance. Note that you are still firmly on the ground while digging but after you have finished digging the model will be in the air. Crouching and uncrouching will fix that.

**Comment by Predatoria** [comment] 2020-06-24 00:35
Duplicate of issue 195.  I'm going to close this.

**Closed as completed by Predatoria** 2020-06-24 00:35 UTC
Labels: bug, Gameplay, tester-team
