### ISSUE TITLE
[Bug] Rubberbanding ptera

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#85] opened 2020-06-15 20:16 UTC
_Originally written by **MysteryKit | 76561198264079326**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
Vendor: GenuineIntel
GPU Brand: AMD Radeon RX 5700
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Only noticed on a ptera on ground or air doesn't matter** 
Map: Rival_Shores

First time playing ptera in ages and it keeps rubberbanding like crazy relogging did not work restarting pc Also didn't work. It keeps rubberbanding in air and while just walking like slowly teleporting back ad fort.

**Comment by Predatoria** [comment] 2020-06-15 20:25
Vague report.  Will not be able to reproduce what sounds like a movement state disagreement between the server and the client off the provided information.  Marking as could not reproduce and closing.

**Closed by Predatoria** 2020-06-15 20:25 UTC
Labels: Can't reproduce, Gameplay, Live, bug
