### ISSUE TITLE
[Bug] Ory Glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#377] opened 2020-08-11 03:36 UTC
_Originally written by **???GOTI??? SpooksHena | 76561198314539087**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: Radeon RX 5500 XT
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ory** 
Map: Rival_Shores

When i pressed Unjam for my ory, it just got me more stuck. i could not move or do anything.

**Comment by cleafspear** [comment] 2020-10-13 23:44
Duplicate of #375

**Closed as completed by cleafspear** 2020-10-13 23:44 UTC
Labels: bug, Gameplay, Live
