### ISSUE TITLE
[Severe Bug] Stuck

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5117] opened 2021-03-15 03:34 UTC
_Originally written by **Wildberry Poptart ??? | 76561197983739707**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **T-Rex** 
Map: Forest_Island

*Replication:* 
Jump in the well, can't get out
Location: X=18875.525 Y=-145791.938 Z=12487.419

**Comment by Predatoria** [comment] 2021-03-17 17:56
Duplicate of player stuck in well

**Closed as completed by Predatoria** 2021-03-17 17:56 UTC
Labels: Severe Bug, Live, Map
