### ISSUE TITLE
[Bug] Resolution Scale at Options Settings

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#647] opened 2020-08-24 22:34 UTC
_Originally written by **Martijn | 76561197970762634**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand:        Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 980
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

My Resolution scale when i increase the slider or whatever its called it always drop back to zero or all the way to the left even when i press apply button

**Comment by Trip-Trap** [comment] 2021-01-08 05:51
Cant reproduce, hope its fixed with the setting remake

**Closed as completed by Trip-Trap** 2021-01-08 05:51 UTC
Labels: bug, Live, Potential fix, Graphics
