### ISSUE TITLE
[Bug] sound&animation issues

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#136] opened 2020-06-18 12:29 UTC
_Originally written by **|UT|GayChicken??? | 76561198345204363**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

when trying to pick up ant nest on rex walking animation stops and rex is just sliding. If you try to pick up stuff while in this state the sound of picking up multiplies and becomes too loud

**Comment by Predatoria** [comment] 2020-06-18 17:26
This is a duplicate of issue 91.  I'm going to close it.

**Closed as completed by Predatoria** 2020-06-18 17:26 UTC
Labels: bug, Live, Animation
