### ISSUE TITLE
[Bug] para weight model being uneven

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#123] opened 2020-06-17 19:51 UTC
_Originally written by **disaster strikes | 76561198040981157**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2070 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **i was just sitting down in a cave after eating a bunch of bushes and noticed my right side was fatter than my skinny left side** 
Map: Rival_Shores

right side of my para model while 100% satiated is fat while the left is skinny like i never ate at all, looks very strange!

not a huge bug or issue but it is odd indeed

**Comment by Predatoria** [comment] 2020-06-18 17:17
I haven't seen this before.  I cannot reproduce it in PIE.  Marking as cannot reproduce and closing.

**Closed as completed by Predatoria** 2020-06-18 17:17 UTC
Labels: bug, Live, Graphics, Can't reproduce
