### ISSUE TITLE
[Severe Bug] Drop bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#206] opened 2020-06-25 01:35 UTC
_Originally written by **S??litary Dreamer | 76561198888153789**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400T CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

Mega was picked up by a mosa (in a mixpack) and when dropped would take damage as if from fall, this happened many times from different mosas. Was on flat ground and all dinos were in the same group. 
Location: X=-55071.500 Y=47322.691 Z=5312.758

**Comment by Predatoria** [comment] 2020-06-27 17:07
I suspect this may be related to the teleport to the origin problem we've seen that causes orys top pop out of the burrow.

**Comment by Predatoria** [comment] 2020-08-15 21:12
Duplicate of 297.  Closing

**Closed as completed by Predatoria** 2020-08-15 21:12 UTC
Labels: Severe Bug, Gameplay, Live, duplicate
