### ISSUE TITLE
[Quality of life] The Velo Camera Problem

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#98] opened 2020-06-16 13:55 UTC
_Originally written by **Dakomi | 76561198449149196**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

*Expected Results:* To the camera behave like normal whilst in a tight space as a Velo.
*Actual Results:* The camera zooms into the Velos body, stopping me from actually seeing anything.
*Replication:* Get into a tight-ish space, against a rock and it will happen.

**Comment by Predatoria** [comment] 2020-06-16 16:43
I cannot reproduce any velo-related camera issues in PIE.  I suspect this is a duplicate of the other bug that was marked fixed on tester where velo's camera would clip into the body if it was crouching, sitting, or laying down on a slope.

**Closed as completed by Predatoria** 2020-06-16 16:43 UTC
Labels: Quality of life, Live, Can't reproduce, Animation
