### ISSUE TITLE
[Major Bug] ı am stuck help me pls

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#5526] opened 2021-03-26 16:38 UTC
_Originally written by **Vankomisin | 76561198073061305**_
Game Version: 1.1.1135

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 4600
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **REX** 
Map: Forest_Island

Location: X=-4077.753 Y=-80876.078 Z=6618.062
ı am stuck help me pls

**Comment by cleafspear** [comment] 2021-03-27 20:13
duplicate of #5516

**Closed as completed by cleafspear** 2021-03-27 20:13 UTC
Labels: Major Bug, Gameplay, Live
