### ISSUE TITLE
[Bug] Sai sprint up hill with food

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#169] opened 2020-06-21 03:25 UTC
_Originally written by **Anubis Deku | 76561199001075987**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce RTX 2080 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Context: **Sai on The Edge of Extinction** 
Map: Rival_Shores

While carrying food (ferns) up an incline, I slow down when pressing the sprint button, the opposite of what should happen. I move faster if I do not press the sprint button.

**Comment by Predatoria** [comment] 2020-06-21 03:50
This is a duplicate of a confirmed fix on tester, issue 135.

**Closed as completed by Predatoria** 2020-06-21 03:50 UTC
Labels: bug, Gameplay, tester-team
