### ISSUE TITLE
[Bug] Ichthys Floating

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#216] opened 2020-06-25 22:23 UTC
_Originally written by **?????d??t???Teawynage | 76561198405825456**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Ichthy** 
Map: Ancestral_Plains

Ichthys floating when laying down or sitting.

**Comment by Trip-Trap** [comment] 2020-06-26 13:52
Can't reproduce. Wonder if they meant that creatures - except for velo i think - don't have terrain alignment when sitting down and sleeping.

**Comment by Predatoria** [comment] 2020-06-26 14:44
I'm not sure.  Either that, or there's a place on the map with invisible collision that causes all animals to float.  Nonetheless, I'm going to close this issue.

**Closed as completed by Predatoria** 2020-06-26 14:44 UTC
Labels: bug, Live, Can't reproduce, Animation
