### ISSUE TITLE
[Bug] Pick up Glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#727] opened 2020-08-29 04:46 UTC
_Originally written by **Moma_Karma | 76561198073738676**_
Game Version: 1.1.1008

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
Map: Rival_Shores

a friend was going to pick up a baby pachy when the pachy glitched behind it while still being held

**Comment by Predatoria** [comment] 2020-08-29 19:31
This is a duplicate of a known grab issue.

**Closed as completed by Predatoria** 2020-08-29 19:31 UTC
Labels: bug, Live, Animation
