### ISSUE TITLE
[Bug] egg bugg

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#321] opened 2020-07-27 18:31 UTC
_Originally written by **???????????????????????????????? | 76561198306686760**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1060 6GB
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Rex** 
Map: Rival_Shores

whenever i breed with friends etc, the babies are born with -2 talent points right after hatching. In the beginning that was not the case, but now it doesn't matter who makes an egg with whom, all babies hatch with -2 talent points for days. and no we do not have incest. But brooding and raising are not worth it.

**Comment by Predatoria** [comment] 2020-07-27 20:36
Sounds like user error to me.  Incest / low comfort is very likely the cause.  Marking this as not enough info / cannot reproduce.

**Closed as completed by Predatoria** 2020-07-27 20:36 UTC
Labels: bug, Gameplay, Live, Can't reproduce, Not enough info
