### ISSUE TITLE
[Bug] blury screen

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#93] opened 2020-06-16 04:43 UTC
_Originally written by **Midnight Reaper | 76561199013588269**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: Radeon RX 580 Series
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

when i go in a cave and picked up and gets dropped my screens goes blury sceen and i have to log to get it off
Location: X=-217283.297 Y=22820.924 Z=21860.580

**Comment by Thy-Vipe** [comment] 2020-06-16 12:37
duplicate of #81

**Closed by Thy-Vipe** 2020-06-16 12:37 UTC
Labels: Live, Map, bug
