### ISSUE TITLE
[Bug] escape menu

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#97] opened 2020-06-16 11:19 UTC
_Originally written by **Lnxarr | 76561198799611773**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

was trying to change dino and escape menu popped up and cant get out of it

**Comment by Predatoria** [comment] 2020-06-16 16:44
I'd need more information to reproduce this.  Marking as cannot reproduce and closing.

**Closed by Predatoria** 2020-06-16 16:44 UTC
Labels: Can't reproduce, Live, UI, bug
