### ISSUE TITLE
[Severe Bug] Growth Roleback

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#95] opened 2020-06-16 09:11 UTC
_Originally written by **Jessy.Christine | 76561198287700499**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 950
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Rex** 
Map: Rival_Shores

Got my rex to 1.162 and logged off before the server restart. Come back after the server restarts to be back at 1.14. My packmate's grade is back to C grade when we were B. We spent over an hour online together.

**Comment by Thy-Vipe** [comment] 2020-06-16 12:30
duplicate of #96

**Closed by Thy-Vipe** 2020-06-16 12:30 UTC
Labels: Gameplay, Live, Severe Bug
