### ISSUE TITLE
[Bug] Group searcher

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#84] opened 2020-06-15 19:04 UTC
_Originally written by **{BG} Modon55 [GER] ??? | 76561198833882155**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Ancestral_Plains

If I will back to a menu, and click on arrow to back, No menu is opening. Please fix that.

**Comment by Predatoria** [comment] 2020-06-15 20:15
This is intended functionality.  The back arrow should return the player to the game, not return them to the escape menu.  Closing this as not a bug / not fixing.

**Closed by Predatoria** 2020-06-15 20:15 UTC
Labels: Live, UI, bug, wontfix
