### ISSUE TITLE
[Bug] Velos behaving strange when leaving ory borrows

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#191] opened 2020-06-22 22:26 UTC
_Originally written by **Spooky Spooks | 76561198040926907**_
Game Version: 1.1.952

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) HD Graphics 530
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Velo** 
Map: Rival_Shores

When a velo goes to exit a borrow their body doesn't teleport to the dirt when climbing out, causing them to ether stand in place or roll around in the tunnels as they exit.

**Comment by Trip-Trap** [comment] 2020-06-22 23:08
Ory does a similar thing, where it will go back down to the ground while leaving the burrow while jumping, instead of being anchored to the burrow exit.

**Comment by Predatoria** [comment] 2020-06-24 00:29
Very similar issue to 189, it's caused by the same code change.  Should be fixed next patch!

**Closed as completed** 2020-06-24 13:30 UTC
Labels: bug, Gameplay, tester-team, Potential fix, Fixed!
