### ISSUE TITLE
[Enhancement] Players mixpacking and trapping others. Quality of Life. Enhancement.

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#4193] opened 2021-02-05 02:32 UTC
_Originally written by **PHOBIE | 76561198026852053**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Vendor: GenuineIntel
GPU Brand: Intel(R) UHD Graphics 630
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Eating flowers near a bridge.** 
Map: Ancestral_Plains

People who are banned on other servers will search official servers without admin and break rules. People will break rules if admin is not on. 

Mixpacking is happening all the time. It is uncommon to meet a herd or pack who do not have a flock of birds to chase the prey down they are too lazy to hunt.

Chat is often toxic and adult. Children should never be allowed to play this game for this reason, which is just sad. Better admin and more admin uptime could fix this.

Players use graphics settings or cheats to detect others from far away. It is not uncommon being spotted and hunted from 1.2 km discovery distance, regardless of natural barriers or line of sight with pinpoint accuracy.

People are losing the will to play high maintenance or slow dinos. This means they will naturally migrate to become bird players, which will exacerbate above problems. People are bullied from the servers and game when their investment is killed. There should be a Dino insurance so veteran players do not have to start from scratch, and that discourages bullying. There is no job other than killing, and this makes the game boring and toxic. Best of luck.

**Comment by TeaTimeJess** [comment] 2021-02-10 20:08
Not a bug, general feedback.

**Comment by cleafspear** [comment] 2021-02-14 07:24
closing as feedback. most of this is admin management of the server.

**Closed as completed by cleafspear** 2021-02-14 07:24 UTC
Labels: Enhancement, Gameplay, Live
