### ISSUE TITLE
[Quality of life] Icthy Shimmer bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#353] opened 2020-08-07 21:08 UTC
_Originally written by **Ra'va | 76561198039772275**_
Game Version: 1.1.993

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Icthy** 
Map: Rival_Shores

Claws and spikes colour region seems to be stuck on brown for me

**Comment by Trip-Trap** [comment] 2020-08-13 16:12
Either can't reproduce or was fixed in the recent patch

**Closed as completed by Trip-Trap** 2020-08-13 16:12 UTC
Labels: Quality of life, Graphics, Can't reproduce, public_testing
