### ISSUE TITLE
[Major Bug] Apato food poisoning glitch

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#407] opened 2020-08-12 02:25 UTC
_Originally written by **{APEX}Ryliebeast | 76561198208439335**_
Game Version: 1.1.1000

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Apato** 
Map: Rival_Shores

Any time as an Apato and I eat tree's (all types) I get food poisoning that lasts forever, (over 20 minutes with crystals n flowers.)

**Comment by Predatoria** [comment] 2020-08-12 16:57
I suspect they were eating underground ory mushrooms.  I should have this fixed next patch, and I'll label that bug fix as pertaining to this report.

I cannot otherwise get apato to get food poisoning from eating regular vegetation such as trees.

**Comment by Predatoria** [comment] 2020-08-12 17:00
Duplicate of 405.

**Closed as completed by Predatoria** 2020-08-12 17:00 UTC
Labels: Major Bug, Gameplay, Live, Potential fix, duplicate
