### ISSUE TITLE
[Bug] The menu is bugged

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#171] opened 2020-06-21 08:40 UTC
_Originally written by **???TIH??? Frank | 76561198212490031**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1660 Ti
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

So how I came across this is when I was respawning I pressed escape whlie loading back to the save slots and therefore bugged the Escape menu to stay stuck on the screen.

**Comment by Thy-Vipe** [comment] 2020-06-21 12:11
duplicate of #170

**Closed as completed by Thy-Vipe** 2020-06-21 12:11 UTC
Labels: bug, UI, Live
