### ISSUE TITLE
[Bug] Being able to move while sleeping

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#90] opened 2020-06-16 01:08 UTC
_Originally written by **MaroonCookie | 76561198284650685**_
Game Version: 1.1.940

*===== System Specs =====
CPU Brand: AMD FX(tm)-6350 Six-Core Processor             
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GT 1030
GPU Driver Info: Unknown
Num CPU Cores: 3
===================*
Map: Rival_Shores

I was picked up while about to transition into sleeping, and when I was put down I was able to move around and jump normally except that I was sleeping. idk if this helps but here's a replay i got of it https://gyazo.com/006c77edb4a2ad3514c7d205f516be33

**Comment by Thy-Vipe** [comment] 2020-06-16 12:46
This is a funny one. Looks like a state jam. What do you think @Predatoria

**Comment by Predatoria** [comment] 2020-06-16 16:54
I think it looks adorable.  I can try to reproduce this.

**Comment by Predatoria** [comment] 2020-06-16 16:59
I'm unable to reproduce it.  I tried to put the sit to lie animation play rate down real slow and then picked myself up in PIE with another client.  It didn't jam. @Peter22FIN have you seen this before?

**Comment by Peter22FIN** [comment] 2020-06-16 17:11
Haha. I have never seen that before.

**Comment by Predatoria** [comment] 2020-06-16 18:12
I'm going to mark this as cannot reproduce and close it.

**Closed by Predatoria** 2020-06-16 18:12 UTC
Labels: Animation, Can't reproduce, Live, bug
