### ISSUE TITLE
[Bug] Cannot be Female

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#266] opened 2020-07-05 16:08 UTC
_Originally written by **Hotdog | 76561198298189256**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Apato** 
Map: Rival_Shores

Every time I try to spawn a Female Apato it will make me a male whenever I spawn in.

**Comment by Predatoria** [comment] 2020-07-05 19:55
I heard this mentioned in tester chat.  Unfortunately, I have absolutely no idea how to reproduce it.

**Comment by Predatoria** [comment] 2020-07-27 19:59
Closing this due to not being able to reproduce it.

**Closed as completed by Predatoria** 2020-07-27 19:59 UTC
Labels: bug, Gameplay, Live, Can't reproduce
